// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/drug/hospitalAgentDrugConfirmReceipt": {
            "post": {
                "description": "医院管理人员审核药品的代买情况，通过订单ID确认接收状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Drug"
                ],
                "summary": "审核药品代买情况",
                "parameters": [
                    {
                        "type": "string",
                        "description": "订单ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    },
                    "404": {
                        "description": "未找到该订单",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    }
                }
            }
        },
        "/api/drug/physiciansOrderAgentDrug": {
            "post": {
                "description": "医师通过该接口进行药品的代买操作",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Drug"
                ],
                "summary": "医师代买药品",
                "parameters": [
                    {
                        "type": "string",
                        "description": "药品ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    },
                    "404": {
                        "description": "药品未找到",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    }
                }
            }
        },
        "/api/drug/physiciansOrderDelivery": {
            "post": {
                "description": "医师通过该接口进行药品的接单和派送操作",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Drug"
                ],
                "summary": "医师派送药品",
                "parameters": [
                    {
                        "type": "string",
                        "description": "药品ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "派送证书",
                        "name": "certificate",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    },
                    "404": {
                        "description": "药品未找到",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    }
                }
            }
        },
        "/api/drug/queryAllDrug": {
            "get": {
                "description": "分页查询药品信息列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Drug"
                ],
                "summary": "查询所有药品信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    }
                }
            }
        },
        "/api/drug/queryDrugByID": {
            "get": {
                "description": "根据药品ID查询相应的药品信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Drug"
                ],
                "summary": "查询药品信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "药品ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    },
                    "404": {
                        "description": "药品未找到",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    }
                }
            }
        },
        "/api/drug/queryDrugByMedicalId": {
            "get": {
                "description": "根据病历ID查询相关的药品、患者、医生和病历信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Drug"
                ],
                "summary": "根据病历ID查询药品信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "病历ID",
                        "name": "medical_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    },
                    "404": {
                        "description": "未找到相关药品",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    }
                }
            }
        },
        "/api/drug/queryPatientAgentDrugHistory": {
            "get": {
                "description": "患者可以通过该接口查询自己的药品代买历史记录，支持分页",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Drug"
                ],
                "summary": "查询患者药品代买历史记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "是否查询原始记录",
                        "name": "raw",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    },
                    "404": {
                        "description": "未找到记录",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    }
                }
            }
        },
        "/api/drug/queryPhysiciansAgentHistoryRecord": {
            "get": {
                "description": "医师可以通过该接口查询自己代卖的药品历史记录，支持分页",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Drug"
                ],
                "summary": "查询医师代卖药品历史记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "是否查询原始记录",
                        "name": "raw",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    },
                    "404": {
                        "description": "未找到记录",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    }
                }
            }
        },
        "/api/inquiry/createInquiryRecord": {
            "post": {
                "description": "创建一个新的问诊记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Inquiry"
                ],
                "summary": "创建问诊记录",
                "parameters": [
                    {
                        "description": "问诊记录信息",
                        "name": "inquiryRecord",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bo.CreateInquiryBo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    }
                }
            }
        },
        "/api/inquiry/queryAllInquiryRecord": {
            "get": {
                "description": "管理员可以查询所有问诊记录，并可以通过状态过滤记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Inquiry"
                ],
                "summary": "查询所有问诊记录",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "问诊状态 (1: 已经问诊结束, 2: 未问诊, 3: 未指派医师, 4: 代接诊, 5: 问诊结束未审核的记录)",
                        "name": "isInquiry",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码 (默认为1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页记录数 (默认为10)",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseBuild"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "bo.CreateInquiryBo": {
            "type": "object",
            "required": [
                "appointment_time",
                "inquiry_detail",
                "reserved_phone",
                "type"
            ],
            "properties": {
                "appointment_time": {
                    "type": "string"
                },
                "inquiry_detail": {
                    "type": "string"
                },
                "patient": {
                    "type": "string"
                },
                "reserved_phone": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "response.ResponseBuild": {
            "type": "object"
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8088",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Swagger MedHealth",
	Description:      "This is a sample server celler server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
