server:
  host: 0.0.0.0
  port: 8088
  proxy_url: http://192.168.1.106:8099/ipfs/
  proxy_port: 8099
  grace_stop: false # 优雅停止

mysql:
  username: root
  password: 123456
  host: 192.168.1.106
  port: 23306
  database: med_health
  charset: utf8mb4

mongo:
  url: "mongodb://myusername:mygptpassword@192.168.1.106:27017/fastgpt?authSource=admin&directConnection=true"

upload:
  domain: http://192.168.1.106:8080/ipfs/ # ipfs网管
  max_size: 2GB # 最大上传内存
  ipfs: http://192.168.1.106:5008 # ipfs服务地址
  backup: "./asset/cid/"

redis:
  addr: 192.168.1.106:26379
  password: ""
  db: 0

# 合约配置文件
contract:
  contract_name: MedHealth
  contract_address: 0x8b43e4e197b017cc8f98b4fc63bfd2c3cbdf544f
  contract_abi: '[{"constant":false,"inputs":[{"name":"id","type":"uint256"}],"name":"physicianAcceptDrugDelivery","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"accountAddress","type":"address"},{"name":"role","type":"string"},{"name":"uuid","type":"string"}],"name":"registerAccount","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"id","type":"uint256"}],"name":"hospitalReviewInquiry","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"id","type":"uint256"}],"name":"getDrugDelivery","outputs":[{"name":"","type":"uint256"},{"name":"","type":"uint256"},{"name":"","type":"address"},{"name":"","type":"address"},{"name":"","type":"address"},{"name":"","type":"string"},{"name":"","type":"uint8"},{"name":"","type":"uint8"},{"name":"","type":"uint8"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"id","type":"uint256"}],"name":"physicianRecInquiry","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"id","type":"uint256"}],"name":"hospitalReviewDrugDelivery","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"id","type":"uint256"},{"name":"inquiryType","type":"string"}],"name":"patientRegistrationInquiry","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"id","type":"uint256"}],"name":"getInquiry","outputs":[{"name":"","type":"uint256"},{"name":"","type":"address"},{"name":"","type":"address"},{"name":"","type":"address"},{"name":"","type":"string"},{"name":"","type":"string"},{"name":"","type":"string"},{"name":"","type":"uint8"},{"name":"","type":"uint8"},{"name":"","type":"uint8"},{"name":"","type":"uint8"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"id","type":"uint256"},{"name":"inquiryId","type":"uint256"}],"name":"patientRegDrugDelivery","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"id","type":"uint256"},{"name":"physicianAddress","type":"address"}],"name":"hospitalDisInquiry","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"id","type":"uint256"},{"name":"medicalHash","type":"string"},{"name":"videoHash","type":"string"}],"name":"physicianDiagnosisInquiry","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"id","type":"uint256"},{"name":"certiHash","type":"string"}],"name":"physicianDeliveryDrug","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"accountAddress","type":"address"}],"name":"getAccount","outputs":[{"name":"","type":"address"},{"name":"","type":"string"},{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[],"payable":false,"stateMutability":"nonpayable","type":"constructor"}]'
  owner: 0xa22ac65be61a6068d17037deecac0d1b221e4e52
  server_host: "http://192.168.1.106:5002"
  trans_url: "/WeBASE-Front/trans/handle"
  parse_url: "/WeBASE-Front/tool/decode"
  account_url: "/WeBASE-Front/privateKey?type=0&userName="

# 默认管理员账号密码
defaultAdmin:
  username: admin
  password: admin

log:  # 日志管理服务
  level: debug  # 日志输出级别
  open: true  # 是否开启日志文件输出服务
  clean_cycle: 7  # 日志清理周期
  out_path: log  # 日志输出路径
  prefix: MediaNeighbor  # 日志文件前缀
  maxsize: 10  # 每个日志文件的最大大小
  compress: true #启用日志压缩
  backup: 7 #保留旧的文件个数

ai: # AI
  url: http://192.168.1.106:3001/v1/chat/completions # 服务地址
  model: glm-4
  authorization: Bearer sk-fastgptnb
  prompt:
    # 问诊总结话术
    sum_up_inquiry: "你现在是一名病历生成助手，下面是用户与AI的对话记录，请你分析这些对话记录去总结生成一分病历总结，简短易懂一段话"
  #是否开启聊天记录mongo监听
  watch_mongo_chat: true
  # AI服务总开关
  open_ai_server: true

mock: # Mock模拟数据生成服务
  open: true # 是否开启服务
  abs_path: "./asset/txt" #资源绝对路径
  asset_file_name: #随机资源文件名称
    # 随机问诊话术
    inquiry_detail: "inquiryDetail.txt"
    # 随机问诊视频
    inquiry_video: "inquiryVideo.txt"
    # 随机医疗单
    medical_img: "medicalImg.txt"
    # 随机药物派送凭证
    drug_deliver_certificate: "drugDeliverCertificate.txt"

authorizationFilter:  # 权限认证路径管理
  jwt_key: "med_health_key_@key"
  need_authorization_api_list: #需要权限认证的接口
    - /api/user/queryUserMessage
    - /api/inquiry/queryPatientInquiryRecord
    - /api/inquiry/queryPhysicianInquiryRecord
    - /api/inquiry/createInquiryRecord
    - /api/inquiry/physicianReception
    - /api/drug/queryPatientAgentDrugHistory
    - /api/drug/queryPhysiciansAgentHistoryRecord
    - /api/drug/patientAgentDrugConfirmReceipt
    - /api/drug/physiciansOrderAgentDrug
    - /api/drug/physiciansOrderDelivery
    - /api/medical/medicalRegistration
    - /api/ai/getMedicalSum

